conv1=/home/nghiant/git/vdsr/backup/idag_3299/core0
conv2=/home/nghiant/git/vdsr/backup/idag_3299/core1
conv3=/home/nghiant/git/vdsr/backup/idag_3299/core2
conv4=/home/nghiant/git/vdsr/backup/idag_3299/core3
conv5=/home/nghiant/git/vdsr/backup/idag_3299/core4
conv6=/home/nghiant/git/vdsr/backup/idag_3299/core5
conv7=/home/nghiant/git/vdsr/backup/idag_3299/core6
conv8=/home/nghiant/git/vdsr/backup/idag_3299/core7