conv1=/home/nghiant/git/vdsr/backup/idag_3301/core0
conv2=/home/nghiant/git/vdsr/backup/idag_3301/core1
conv3=/home/nghiant/git/vdsr/backup/idag_3301/core2
conv4=/home/nghiant/git/vdsr/backup/idag_3301/core3
conv5=/home/nghiant/git/vdsr/backup/idag_3301/core4
conv6=/home/nghiant/git/vdsr/backup/idag_3301/core5
conv7=/home/nghiant/git/vdsr/backup/idag_3301/core6
conv8=/home/nghiant/git/vdsr/backup/idag_3301/core7